"""Onboarding wizard helpers.

Validates Discord credentials live, generates a populated `.env`
and (optionally) a `docker-compose.yml`, and tracks a sentinel file so the
wizard knows whether to greet a returning user with the search SPA instead.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import httpx
from pydantic import BaseModel, Field

from autopoints.config import settings


SENTINEL_FILENAME = ".onboarded"


class DiscordTestRequest(BaseModel):
    token: str


class TestResult(BaseModel):
    ok: bool
    error: str | None = None
    bot_username: str | None = None


class OnboardStatus(BaseModel):
    configured: bool
    discord_present: bool
    sentinel_exists: bool


class DiscordConfig(BaseModel):
    enabled: bool = False
    token: str = ""
    guild_id: str = ""
    notify_channel_id: str = ""
    run_interval_minutes: int = 60
    demo_mode: bool = False


class GenerateRequest(BaseModel):
    mode: Literal["local", "nas"] = "local"
    services: list[Literal["web", "discord", "autoruns"]] = Field(default_factory=list)
    discord: DiscordConfig = DiscordConfig()


class GenerateResponse(BaseModel):
    env: str
    compose: str | None = None


# ----- live tests -----


async def test_discord(req: DiscordTestRequest) -> TestResult:
    """Verify a Discord bot token by calling /users/@me with `Bot <token>`."""
    try:
        async with httpx.AsyncClient(timeout=10.0) as c:
            resp = await c.get(
                "https://discord.com/api/v10/users/@me",
                headers={"Authorization": f"Bot {req.token}"},
            )
    except httpx.HTTPError as e:
        return TestResult(ok=False, error=f"network: {e}")

    if resp.status_code == 200:
        body = resp.json()
        username = body.get("username") or "(unknown)"
        disc = body.get("discriminator") or "0"
        if disc and disc != "0":
            username = f"{username}#{disc}"
        return TestResult(ok=True, bot_username=username)
    return TestResult(ok=False, error=f"{resp.status_code}: {resp.reason_phrase}")


# ----- sentinel -----


def sentinel_path() -> Path:
    return settings.cache_path().parent / SENTINEL_FILENAME


def is_configured() -> OnboardStatus:
    sentinel = sentinel_path().exists()
    import os
    discord = bool(os.getenv("DISCORD_BOT_TOKEN"))
    return OnboardStatus(
        configured=sentinel or discord,
        discord_present=discord,
        sentinel_exists=sentinel,
    )


def mark_complete() -> None:
    p = sentinel_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.touch()


def unmark_complete() -> None:
    p = sentinel_path()
    if p.exists():
        p.unlink()


# ----- generation -----


def generate_env(req: GenerateRequest) -> str:
    lines: list[str] = [
        "# autopoints — generated by the onboarding wizard",
        "# Copy this to `.env` next to your docker-compose.yml.",
        "",
    ]
    if req.discord.enabled and req.discord.token:
        lines += [
            "# Discord bot",
            f"DISCORD_BOT_TOKEN={req.discord.token}",
        ]
        if req.discord.guild_id:
            lines.append(f"DISCORD_GUILD_ID={req.discord.guild_id}")
        if "autoruns" in req.services:
            if req.discord.notify_channel_id:
                lines.append(f"DISCORD_NOTIFY_CHANNEL_ID={req.discord.notify_channel_id}")
            lines.append(f"DISCORD_RUN_INTERVAL_MINUTES={req.discord.run_interval_minutes}")
        if req.discord.demo_mode:
            lines.append("DISCORD_DEMO_MODE=1")
        lines.append("")

    if req.mode == "nas":
        lines += [
            "# NAS-specific paths",
            "AUTOPOINTS_CACHE_PATH=/data/cache.db",
            "",
        ]

    return "\n".join(lines)


def generate_compose(req: GenerateRequest) -> str:
    """Produce a complete docker-compose.yml tailored to the chosen services.

    Always includes the `web` service (the wizard itself lives there).
    Includes `discord` only if requested. Includes Watchtower for auto-update.
    """
    parts = [
        "# autopoints — generated by the onboarding wizard",
        "# Save as docker-compose.yml next to your .env",
        "",
        "services:",
        "  web:",
        "    image: ghcr.io/kushrp/autopoints:latest",
        "    container_name: autopoints-web",
        "    pull_policy: always",
        '    ports:',
        '      - "8000:8000"',
        '    volumes:',
        '      - autopoints-data:/data',
        '    env_file:',
        '      - .env',
        "    environment:",
        "      AUTOPOINTS_CACHE_PATH: /data/cache.db",
        "    restart: unless-stopped",
        "    labels:",
        '      com.centurylinklabs.watchtower.enable: "true"',
    ]

    if "discord" in req.services:
        parts += [
            "",
            "  discord:",
            "    image: ghcr.io/kushrp/autopoints:latest",
            "    container_name: autopoints-discord",
            "    pull_policy: always",
            '    command: ["python", "-m", "autopoints.discord_bot.server"]',
            "    volumes:",
            "      - autopoints-data:/data",
            "    env_file:",
            "      - .env",
            "    environment:",
            "      AUTOPOINTS_CACHE_PATH: /data/cache.db",
            "    restart: unless-stopped",
            "    depends_on:",
            "      - web",
            "    labels:",
            '      com.centurylinklabs.watchtower.enable: "true"',
        ]

    parts += [
        "",
        "  watchtower:",
        "    image: containrrr/watchtower:latest",
        "    container_name: autopoints-watchtower",
        "    volumes:",
        "      - /var/run/docker.sock:/var/run/docker.sock",
        "    environment:",
        '      WATCHTOWER_LABEL_ENABLE: "true"',
        '      WATCHTOWER_POLL_INTERVAL: "300"',
        '      WATCHTOWER_CLEANUP: "true"',
        "    restart: unless-stopped",
        "",
        "volumes:",
        "  autopoints-data:",
        "    name: autopoints-data",
    ]
    return "\n".join(parts) + "\n"


def generate(req: GenerateRequest) -> GenerateResponse:
    return GenerateResponse(
        env=generate_env(req),
        compose=generate_compose(req) if req.mode == "nas" else None,
    )
