from __future__ import annotations

import pytest
import respx
from fastapi.testclient import TestClient
from httpx import Response

from autopoints.api.main import app
from autopoints.api.onboard import (
    DiscordConfig,
    GenerateRequest,
    generate,
    is_configured,
    mark_complete,
    sentinel_path,
)
from autopoints.config import settings

client = TestClient(app)


@pytest.fixture(autouse=True)
def _isolated_storage(tmp_path, monkeypatch):
    monkeypatch.setattr(settings, "autopoints_cache_path", tmp_path / "cache.db")
    monkeypatch.delenv("DISCORD_BOT_TOKEN", raising=False)


def test_status_unconfigured(tmp_path, monkeypatch):
    monkeypatch.setattr(settings, "autopoints_cache_path", tmp_path / "c.db")
    monkeypatch.delenv("DISCORD_BOT_TOKEN", raising=False)
    s = is_configured()
    assert s.configured is False
    assert s.discord_present is False
    assert s.sentinel_exists is False


def test_status_discord_configured(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "autopoints_cache_path", tmp_path / "c.db")
    monkeypatch.setenv("DISCORD_BOT_TOKEN", "tok")
    s = is_configured()
    assert s.configured is True
    assert s.discord_present is True


def test_status_sentinel(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "autopoints_cache_path", tmp_path / "c.db")
    mark_complete()
    s = is_configured()
    assert s.configured is True
    assert s.sentinel_exists is True


def test_complete_and_reset_lifecycle(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "autopoints_cache_path", tmp_path / "c.db")
    r = client.post("/api/onboard/complete")
    assert r.status_code == 200
    assert sentinel_path().exists()
    r = client.delete("/api/onboard/complete")
    assert r.status_code == 200
    assert not sentinel_path().exists()


def test_index_redirects_when_unconfigured():
    r = client.get("/", follow_redirects=False)
    assert r.status_code == 307
    assert r.headers["location"] == "/onboard"


def test_index_renders_spa_when_configured(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "autopoints_cache_path", tmp_path / "c.db")
    mark_complete()
    r = client.get("/")
    assert r.status_code == 200
    assert "search-form" in r.text


def test_onboard_page_always_accessible():
    r = client.get("/onboard")
    assert r.status_code == 200
    assert "onboard" in r.text.lower()


@respx.mock
def test_discord_test_success():
    respx.get("https://discord.com/api/v10/users/@me").mock(
        return_value=Response(200, json={"username": "autopoints", "discriminator": "0"})
    )
    r = client.post("/api/onboard/test/discord", json={"token": "MTIz..."})
    body = r.json()
    assert body["ok"] is True
    assert body["bot_username"] == "autopoints"


@respx.mock
def test_discord_test_legacy_discriminator():
    respx.get("https://discord.com/api/v10/users/@me").mock(
        return_value=Response(200, json={"username": "autopoints", "discriminator": "1234"})
    )
    r = client.post("/api/onboard/test/discord", json={"token": "x"})
    assert r.json()["bot_username"] == "autopoints#1234"


@respx.mock
def test_discord_test_unauthorized():
    respx.get("https://discord.com/api/v10/users/@me").mock(
        return_value=Response(401, json={"message": "401: Unauthorized"})
    )
    r = client.post("/api/onboard/test/discord", json={"token": "bad"})
    body = r.json()
    assert body["ok"] is False
    assert "401" in body["error"]


def test_generate_env_local_minimal():
    out = generate(
        GenerateRequest(
            mode="local",
            services=["web"],
        )
    )
    assert "generated by the onboarding wizard" in out.env
    assert "DISCORD_BOT_TOKEN" not in out.env
    assert out.compose is None


def test_generate_env_nas_with_discord_and_autoruns():
    out = generate(
        GenerateRequest(
            mode="nas",
            services=["web", "discord", "autoruns"],
            discord=DiscordConfig(
                enabled=True, token="DISCORD_TOK", guild_id="g1",
                notify_channel_id="c1", run_interval_minutes=30,
            ),
        )
    )
    assert "DISCORD_BOT_TOKEN=DISCORD_TOK" in out.env
    assert "DISCORD_GUILD_ID=g1" in out.env
    assert "DISCORD_NOTIFY_CHANNEL_ID=c1" in out.env
    assert "DISCORD_RUN_INTERVAL_MINUTES=30" in out.env
    assert "AUTOPOINTS_CACHE_PATH=/data/cache.db" in out.env
    assert out.compose is not None
    assert "ghcr.io/kushrp/autopoints:latest" in out.compose
    assert "autopoints-discord" in out.compose
    assert "watchtower" in out.compose


def test_generate_compose_omits_discord_when_not_selected():
    out = generate(
        GenerateRequest(
            mode="nas",
            services=["web"],
        )
    )
    assert out.compose is not None
    assert "autopoints-discord" not in out.compose
    assert "autopoints-web" in out.compose
    assert "watchtower" in out.compose


def test_generate_endpoint():
    r = client.post(
        "/api/onboard/generate",
        json={
            "mode": "local",
            "services": ["web"],
            "discord": {"enabled": False, "token": "", "guild_id": "", "notify_channel_id": "",
                        "run_interval_minutes": 60, "demo_mode": False},
        },
    )
    assert r.status_code == 200, r.text
    body = r.json()
    assert "generated by the onboarding wizard" in body["env"]
    assert body["compose"] is None
